### PR TITLE
Reduce measure errors

### PR DESCRIPTION
**Pull request by JanHBade**
From another lib: https://github.com/gamegine/HCSR04-ultrasonic-sensor-lib/pull/3

### CODE REVIEW

**Comment by JanHBade** [comment]
@Martinsos hello?

**Comment by Martinsos** [comment]
Hey @JanHBade ! I am pretty slammed recently so don't have much time to review the PRs here, sorry for the delay. 

Url got modified to point to your repo -> that should be reverted.
There is some issue with indentation also.
We should also add a coment that explains why this was added, since it is not obvious.

Finally, I would love to be fully convinced this is the right change. I saw that other PR and mentioning of certain source file but I don't know where to find it -> any way you can point me to it? Also, how confident are you in this change, anythign that could go wrong with it? How mcuh do you understand about it?

**Comment by JanHBade** [comment]
made an new one #16

**Comment by Martinsos** [comment]
@JanHBade why new one? And you didn't asnwer my questions.

**Pull request closed without merging**
